<a href="https://colab.research.google.com/github/DishaAdiga/VTU_AIML_Lab/blob/main/Prog3_Back_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
input_layer_neuron = 2
hidden_layer_neuron=3
output_neuron = 1

print("Input layer neurons = ",input_layer_neuron)
print("Hidden layer neurons = ",hidden_layer_neuron)
print("Output neurons = ",output_neuron)

Input layer neurons =  2
Hidden layer neurons =  3
Output neurons =  1


In [2]:
wh = np.random.uniform(size=(input_layer_neuron, hidden_layer_neuron))
print("Weights from input layer to hidden layer = ",wh)

Weights from input layer to hidden layer =  [[0.39028667 0.91829848 0.19458213]
 [0.76151257 0.48307799 0.66825529]]


In [3]:
bh = np.random.uniform(size=(1,hidden_layer_neuron))
print("Bias between input layer and hidden layer = ", bh)

Bias between input layer and hidden layer =  [[0.4016775  0.67324609 0.20479871]]


In [4]:
wout = np.random.uniform(size=(hidden_layer_neuron, output_neuron))
print("Weights from hidden layer to output layer = ",wout)

Weights from hidden layer to output layer =  [[0.75989842]
 [0.25899312]
 [0.05315303]]


In [5]:
bout = np.random.uniform(size=(1,output_neuron))
print("Bias between hidden layer and output layer = ",bout)

Bias between hidden layer and output layer =  [[0.33400573]]


In [7]:
epoch = 7000
lr=0.1
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x=x/np.amax(x,axis=0)
print(x)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


In [9]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def derivatives_sigmoid(x):
  return x*(1-x)

for i in range (epoch):
  hinp1 = np.dot(x,wh)
  hinp=hinp1+bh
  h1layer_act = sigmoid(hinp)
  outinp1 = np.dot(h1layer_act, wout)
  outinp = outinp1+bout
  output=sigmoid(outinp)
  eo = y-output
  outgrad = derivatives_sigmoid(output)
  d_output = eo * outgrad
  eh = d_output.dot(wout.T)
  hiddengrad = derivatives_sigmoid(h1layer_act)
  d_hiddenlayer = eh * hiddengrad
  wout+=h1layer_act.T.dot(d_output)*lr
  wht = x.T.dot(d_hiddenlayer)*lr

  print("Input: \n",str(x))
  print("Actual output: \n",str(y))
  print("Predicted output: ",output)

Streaming output truncated to the last 5000 lines.
 [[92.]
 [86.]
 [89.]]
Predicted output:  [[0.99999828]
 [0.99999379]
 [0.99999796]]
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
 [[92.]
 [86.]
 [89.]]
Predicted output:  [[0.99999828]
 [0.99999379]
 [0.99999797]]
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
 [[92.]
 [86.]
 [89.]]
Predicted output:  [[0.99999828]
 [0.99999379]
 [0.99999797]]
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
 [[92.]
 [86.]
 [89.]]
Predicted output:  [[0.99999828]
 [0.99999379]
 [0.99999797]]
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
 [[92.]
 [86.]
 [89.]]
Predicted output:  [[0.99999828]
 [0.99999379]
 [0.99999797]]
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
 [[92.]
 [86.]
 [89